module.exports = {
  users: "users",
  customers: "customers",
  customer_gsts: "customer_gsts",
  addresses: "addresses",
  brands: "brands",
  carts: "carts",
  cartItems: "cart_items",
  categories: "categories",
  subCategories: "sub_categories",
  orders: "orders",
  orderItems: "order_items",
  products: "products",
  productVariants: "product_variants",
  numberOtps: "number_otps",
  delivery_partner: "delivery_partner",
  product_images: "product_images",
};
